version: '3.7'

services:
  nginx:
    image: nginx:${NGINX_VERSION:-1.19-alpine-perl}
    restart: unless-stopped

    volumes:
      - ${CERT_DIR:-./certs}:/etc/nginx/ssl:ro
      - ${LOG_DIR:-./instance/logs}/nginx/:/var/log/nginx/:rw
      - ${NGINX_CONF_DIR:-./configs/nginx-conf}/local:/etc/nginx/conf.d/local
      - ${NGINX_CONF_DIR:-./configs/nginx-conf}/nginx.conf:/etc/nginx/nginx.conf


    ports:
      - "80:80"
      - "443:443"

    networks:
      - frontend

networks:
  frontend: